"""The version a build carries, and the stamp that tells it which one it is.

`BASE_VERSION` is the only version written by hand. A release takes its number
from the run that publishes it (see the `version` job in
`.github/workflows/build.yml`):

* a push to `main` publishes `v<major>.<minor>.<run number>` - the patch is the
  Actions run number, which only grows, so an installed copy can always tell a
  newer release from an older one;
* a `v1.2.3` tag publishes exactly that version, for a release worth naming.

The number a build reports is written into `_buildinfo.py` at build time - by
`build.py` and by the APK job - and never checked in: a checkout reports
`BASE_VERSION`, and a build made by hand stamps `BASE_VERSION+local`, which
`update.py` reads as "do not replace me".
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

BASE_VERSION = "1.0.0"
STAMP_MODULE = "_buildinfo"
STAMP_FILE = Path(__file__).resolve().parent / f"{STAMP_MODULE}.py"
# Suffix of a build made by hand, which the updater leaves alone.
LOCAL_SUFFIX = "+local"

_NUMBER = re.compile(r"\A\d+(?:\.\d+)*\Z")


def release(text: str) -> str:
    """`v1.2.3`, `1.2.3+local`, `1.2.3-rc1` -> `1.2.3`: the release it names."""
    return text.strip().lstrip("vV").split("+")[0].split("-")[0]


def parse(text: str) -> tuple[int, ...] | None:
    """Comparable form of a version, or None when it does not name one."""
    number = release(text)
    if not _NUMBER.match(number):
        return None
    return tuple(int(part) for part in number.split("."))


def is_newer(candidate: str, current: str) -> bool:
    """True when `candidate` names a later release than `current`."""
    later, earlier = parse(candidate), parse(current)
    if later is None or earlier is None:
        return False
    width = max(len(later), len(earlier))
    return later + (0,) * (width - len(later)) > earlier + (0,) * (width - len(earlier))


def stamped() -> str | None:
    """The version a build wrote, or None in a source checkout."""
    try:
        from _buildinfo import VERSION
    except ImportError:
        return None
    return str(VERSION)


def current() -> str:
    """The version this process is."""
    return stamped() or BASE_VERSION


def is_local() -> bool:
    """True for a build made by hand, which must not be replaced by a release."""
    return current().endswith(LOCAL_SUFFIX)


def stamp(text: str | None = None) -> Path:
    """Write `_buildinfo.py`; no argument stamps the base version as local."""
    written = text.strip() if text and text.strip() else f"{BASE_VERSION}{LOCAL_SUFFIX}"
    STAMP_FILE.write_text(
        '"""Generated by `version.py --stamp`; not checked in."""\n'
        "\n"
        f'VERSION = "{written}"\n',
        encoding="utf-8",
    )
    return STAMP_FILE


def main(argv: list[str]) -> int:
    """`python version.py` prints the version; `--stamp [VERSION]` writes it."""
    args = argv[1:]
    if not args:
        print(current())
        return 0
    if args[0] == "--stamp" and len(args) <= 2:
        stamp(args[1] if len(args) > 1 else None)
        print(f"{STAMP_FILE.name}: VERSION = {current()!r}")
        return 0
    print(f"usage: {Path(argv[0]).name} [--stamp VERSION]", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
